### ISSUE TITLE
Husky Issues

### ISSUE THREAD

**Issue by aliabudiab** [PepperBot-co/pepperbot#23]
Husky is not invoking pre-commit hooks

**Comment by Yawanseh** [comment]
On pre-installation, it will initiate the Husky folders and install them. You can also do this manually using `npx husky install`. 

There was another issue concerning disk access to the file. This was resolved using `chmod ug+x .husky/*`. (Fixed on `feature/pb-2-chat-and-node-configs-layout` branch)
